import type { SidebarConfig } from '@/lib/types';

/**
 * Configuración del sidebar de la aplicación
 * Define la estructura de menú con roles y permisos
 * 
 * Uso en componentes:
 * import { sidebarConfig } from '@/config/sidebar.config';
 * const visibleMenu = filterMenuByPermissions(sidebarConfig.sections, user);
 */
export const sidebarConfig: SidebarConfig = {
  header: {
    logo: 'F',
    company: 'FERRETERÍA CENTRAL',
    toggleCollapse: true,
  },
  sections: [
    {
      id: 'dashboard',
      label: 'Dashboard',
      icon: 'BarChart3',
      route: '/dashboard',
      roles: ['admin', 'operador'],
      permissions: [],
      children: [
        {
          id: 'dashboard-main',
          label: 'Panel Principal',
          route: '/dashboard',
          icon: 'Home',
          roles: ['admin', 'operador'],
          permissions: [],
        },
        {
          id: 'dashboard-stats',
          label: 'Estadísticas Personales',
          route: '/dashboard/stats',
          icon: 'TrendingUp',
          roles: ['admin', 'operador'],
          permissions: ['analytics.view'],
        },
        {
          id: 'dashboard-tasks',
          label: 'Mis Tareas',
          route: '/dashboard/tasks',
          icon: 'CheckList',
          roles: ['admin', 'operador'],
          permissions: [],
        },
      ],
    },
    {
      id: 'catalogs_section',
      label: 'Catálogos y Referencias',
      icon: 'Boxes',
      route: null,
      roles: ['admin', 'operador'],
      permissions: ['products.view', 'services.view', 'catalogs.view'],
      children: [
        {
          id: 'products',
          label: 'Productos',
          route: '/dashboard/products',
          icon: 'Package',
          roles: ['admin', 'operador'],
          permissions: ['products.view'],
          children: [
            {
              id: 'products-all',
              label: 'Ver Todos',
              route: '/dashboard/products',
              icon: 'Eye',
              roles: ['admin', 'operador'],
              permissions: ['products.view'],
            },
            {
              id: 'products-new',
              label: 'Crear Producto',
              route: '/dashboard/products/new',
              icon: 'Plus',
              roles: ['admin', 'operador'],
              permissions: ['products.create'],
            },
            {
              id: 'products-import',
              label: 'Importar Masivo',
              route: '/dashboard/products/import',
              icon: 'Upload',
              roles: ['admin', 'operador'],
              permissions: ['products.bulk_import'],
            },
          ],
        },
        {
          id: 'services',
          label: 'Servicios',
          route: '/dashboard/services',
          icon: 'Wrench',
          roles: ['admin', 'operador'],
          permissions: ['services.view'],
          children: [
            {
              id: 'services-all',
              label: 'Ver Todos',
              route: '/dashboard/services',
              icon: 'Eye',
              roles: ['admin', 'operador'],
              permissions: ['services.view'],
            },
            {
              id: 'services-new',
              label: 'Crear Servicio',
              route: '/dashboard/services/new',
              icon: 'Plus',
              roles: ['admin', 'operador'],
              permissions: ['services.create'],
            },
          ],
        },
        {
          id: 'categories',
          label: 'Categorías',
          route: '/dashboard/categories',
          icon: 'Tags',
          roles: ['admin'],
          permissions: ['catalogs.categories.manage'],
        },
        {
          id: 'units',
          label: 'Unidades de Medida',
          route: '/dashboard/units',
          icon: 'Ruler',
          roles: ['admin'],
          permissions: ['catalogs.units.manage'],
        },
        {
          id: 'price_lists',
          label: 'Listas de Precios',
          route: '/dashboard/price-lists',
          icon: 'DollarSign',
          roles: ['admin', 'operador'],
          permissions: ['prices.view'],
          children: [
            {
              id: 'price_lists-all',
              label: 'Ver Listas',
              route: '/dashboard/price-lists',
              icon: 'Eye',
              roles: ['admin', 'operador'],
              permissions: ['prices.view'],
            },
            {
              id: 'price_lists-new',
              label: 'Crear Lista',
              route: '/dashboard/price-lists/new',
              icon: 'Plus',
              roles: ['admin'],
              permissions: ['prices.edit'],
            },
          ],
        },
      ],
    },
    {
      id: 'operations_section',
      label: 'Operaciones',
      icon: 'ShoppingCart',
      route: null,
      roles: ['admin', 'operador'],
      permissions: ['sales.view', 'shipping_notes.view', 'quotes.view'],
      badge: 'dynamic',
      children: [
        {
          id: 'sales',
          label: 'Ventas',
          route: '/dashboard/sales',
          icon: 'CreditCard',
          roles: ['admin', 'operador'],
          permissions: ['sales.view'],
          badge: 'dynamic',
          children: [
            {
              id: 'sales-new',
              label: 'Nueva Venta',
              route: '/dashboard/sales/new',
              icon: 'Plus',
              roles: ['admin', 'operador'],
              permissions: ['sales.create'],
            },
            {
              id: 'sales-my',
              label: 'Mis Ventas',
              route: '/dashboard/sales/my',
              icon: 'Eye',
              roles: ['admin', 'operador'],
              permissions: ['sales.view'],
            },
            {
              id: 'sales-all',
              label: 'Todas las Ventas',
              route: '/dashboard/sales/all',
              icon: 'BarChart3',
              roles: ['admin'],
              permissions: ['sales.view_all'],
            },
            {
              id: 'sales-history',
              label: 'Historial',
              route: '/dashboard/sales/history',
              icon: 'History',
              roles: ['admin', 'operador'],
              permissions: ['sales.view'],
            },
          ],
        },
        {
          id: 'shipping_notes',
          label: 'Remitos',
          route: '/dashboard/shipping-notes',
          icon: 'Package',
          roles: ['admin', 'operador'],
          permissions: ['shipping_notes.view'],
          badge: 'dynamic',
          children: [
            {
              id: 'shipping-new',
              label: 'Nuevo Remito',
              route: '/dashboard/shipping-notes/new',
              icon: 'Plus',
              roles: ['admin', 'operador'],
              permissions: ['shipping_notes.create'],
            },
            {
              id: 'shipping-pending',
              label: 'Pendientes de Entrega',
              route: '/dashboard/shipping-notes/pending',
              icon: 'Clock',
              roles: ['admin', 'operador'],
              permissions: ['shipping_notes.view'],
            },
            {
              id: 'shipping-history',
              label: 'Historial',
              route: '/dashboard/shipping-notes/history',
              icon: 'History',
              roles: ['admin', 'operador'],
              permissions: ['shipping_notes.view'],
            },
          ],
        },
        {
          id: 'quotes',
          label: 'Presupuestos',
          route: '/dashboard/quotes',
          icon: 'FileText',
          roles: ['admin', 'operador'],
          permissions: ['quotes.view'],
          badge: 'dynamic',
          children: [
            {
              id: 'quotes-new',
              label: 'Crear Presupuesto',
              route: '/dashboard/quotes/new',
              icon: 'Plus',
              roles: ['admin', 'operador'],
              permissions: ['quotes.create'],
            },
            {
              id: 'quotes-my',
              label: 'Mis Presupuestos',
              route: '/dashboard/quotes/my',
              icon: 'Eye',
              roles: ['admin', 'operador'],
              permissions: ['quotes.view'],
            },
            {
              id: 'quotes-all',
              label: 'Todos los Presupuestos',
              route: '/dashboard/quotes/all',
              icon: 'BarChart3',
              roles: ['admin'],
              permissions: ['quotes.view_all'],
            },
            {
              id: 'quotes-tracking',
              label: 'Seguimiento',
              route: '/dashboard/quotes/tracking',
              icon: 'Map',
              roles: ['admin', 'operador'],
              permissions: ['quotes.track'],
            },
          ],
        },
      ],
    },
    {
      id: 'reports_section',
      label: 'Análisis y Reportes',
      icon: 'BarChart',
      route: null,
      roles: ['admin', 'operador'],
      permissions: ['analytics.view', 'analytics.reports_basic'],
      children: [
        {
          id: 'analytics',
          label: 'Dashboard Analítico',
          route: '/dashboard/analytics',
          icon: 'TrendingUp',
          roles: ['admin', 'operador'],
          permissions: ['analytics.view'],
        },
        {
          id: 'reports-sales',
          label: 'Reportes de Ventas',
          route: '/dashboard/reports/sales',
          icon: 'LineChart',
          roles: ['admin', 'operador'],
          permissions: ['analytics.reports_basic'],
        },
        {
          id: 'reports-inventory',
          label: 'Reportes de Inventario',
          route: '/dashboard/reports/inventory',
          icon: 'Box',
          roles: ['admin', 'operador'],
          permissions: ['analytics.reports_basic'],
        },
        {
          id: 'reports-customers',
          label: 'Reportes de Clientes',
          route: '/dashboard/reports/customers',
          icon: 'Users',
          roles: ['admin', 'operador'],
          permissions: ['analytics.reports_basic'],
        },
        {
          id: 'reports-advanced',
          label: 'Reportes Avanzados',
          route: '/dashboard/reports/advanced',
          icon: 'Zap',
          roles: ['admin'],
          permissions: ['analytics.reports_advanced'],
        },
        {
          id: 'reports-custom',
          label: 'Reportes Personalizados',
          route: '/dashboard/reports/custom',
          icon: 'Settings',
          roles: ['admin'],
          permissions: ['analytics.export_reports'],
        },
      ],
    },
    {
      id: 'admin_section',
      label: 'Administración',
      icon: 'Users',
      route: null,
      roles: ['admin'],
      permissions: ['users.view'],
      children: [
        {
          id: 'users_management',
          label: 'Gestión de Usuarios',
          route: '/dashboard/admin/users',
          icon: 'Users',
          roles: ['admin'],
          permissions: ['users.view'],
          children: [
            {
              id: 'users-all',
              label: 'Ver Todos',
              route: '/dashboard/admin/users',
              icon: 'Eye',
              roles: ['admin'],
              permissions: ['users.view'],
            },
            {
              id: 'users-new',
              label: 'Crear Usuario',
              route: '/dashboard/admin/users/new',
              icon: 'Plus',
              roles: ['admin'],
              permissions: ['users.create'],
            },
            {
              id: 'users-groups',
              label: 'Grupos de Usuarios',
              route: '/dashboard/admin/users/groups',
              icon: 'Users',
              roles: ['admin'],
              permissions: ['users.view'],
            },
          ],
        },
        {
          id: 'roles_permissions',
          label: 'Roles y Permisos',
          route: '/dashboard/admin/roles',
          icon: 'Lock',
          roles: ['admin'],
          permissions: ['users.view'],
          children: [
            {
              id: 'roles-all',
              label: 'Ver Roles',
              route: '/dashboard/admin/roles',
              icon: 'Eye',
              roles: ['admin'],
              permissions: ['users.view'],
            },
            {
              id: 'roles-new',
              label: 'Crear Rol',
              route: '/dashboard/admin/roles/new',
              icon: 'Plus',
              roles: ['admin'],
              permissions: ['users.change_role'],
            },
          ],
        },
        {
          id: 'audit_logs',
          label: 'Auditoría',
          route: '/dashboard/admin/audit',
          icon: 'FileText',
          roles: ['admin'],
          permissions: ['config.audit_logs'],
          children: [
            {
              id: 'audit-logs',
              label: 'Logs de Actividad',
              route: '/dashboard/admin/audit/logs',
              icon: 'FileText',
              roles: ['admin'],
              permissions: ['config.audit_logs'],
            },
            {
              id: 'audit-changes',
              label: 'Historial de Cambios',
              route: '/dashboard/admin/audit/changes',
              icon: 'History',
              roles: ['admin'],
              permissions: ['config.audit_logs'],
            },
            {
              id: 'audit-access',
              label: 'Intentos de Acceso',
              route: '/dashboard/admin/audit/access',
              icon: 'Lock',
              roles: ['admin'],
              permissions: ['config.audit_logs'],
            },
          ],
        },
      ],
    },
    {
      id: 'config_section',
      label: 'Configuración',
      icon: 'Settings',
      route: null,
      roles: ['admin'],
      permissions: ['config.system.view'],
      children: [
        {
          id: 'system_config',
          label: 'Parámetros del Sistema',
          route: '/dashboard/config/system',
          icon: 'Sliders',
          roles: ['admin'],
          permissions: ['config.system.view'],
        },
        {
          id: 'backups',
          label: 'Respaldos',
          route: '/dashboard/config/backups',
          icon: 'HardDrive',
          roles: ['admin'],
          permissions: ['config.backups.create'],
          children: [
            {
              id: 'backups-create',
              label: 'Crear Respaldo',
              route: '/dashboard/config/backups/create',
              icon: 'Plus',
              roles: ['admin'],
              permissions: ['config.backups.create'],
            },
            {
              id: 'backups-view',
              label: 'Ver Respaldos',
              route: '/dashboard/config/backups',
              icon: 'Eye',
              roles: ['admin'],
              permissions: ['config.backups.view'],
            },
            {
              id: 'backups-restore',
              label: 'Restaurar',
              route: '/dashboard/config/backups/restore',
              icon: 'RotateCcw',
              roles: ['admin'],
              permissions: ['config.backups.restore'],
            },
          ],
        },
        {
          id: 'security',
          label: 'Seguridad',
          route: '/dashboard/config/security',
          icon: 'Shield',
          roles: ['admin'],
          permissions: ['config.security.view'],
          children: [
            {
              id: 'security-general',
              label: 'Configuración General',
              route: '/dashboard/config/security',
              icon: 'Settings',
              roles: ['admin'],
              permissions: ['config.security.view'],
            },
            {
              id: 'security-2fa',
              label: '2FA y MFA',
              route: '/dashboard/config/security/2fa',
              icon: 'Key',
              roles: ['admin'],
              permissions: ['config.security.view'],
            },
          ],
        },
        {
          id: 'integrations',
          label: 'Integraciones',
          route: '/dashboard/config/integrations',
          icon: 'Link',
          roles: ['admin'],
          permissions: ['config.integrations'],
        },
      ],
    },
  ],
};
